# NumPy Reshaping

In this notebook, we will learn how to change the shape of a NumPy array.

Topics covered:
- reshape()
- flatten()
- ravel()
- Understanding shape

In [1]:
import numpy as np

## 1. Creating an Array

Let's create a simple 1D array.

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr)
print("Shape:", arr.shape)

[1 2 3 4 5 6]
Shape: (6,)


#  2. reshape()

`reshape()` changes the shape of an array without changing its data.

For example:

6 elements can be arranged as:
- 2 rows × 3 columns
- 3 rows × 2 columns

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)
print("Shape:", new_arr.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## 3. Another Example of reshape()

In [4]:
arr = np.arange(1, 13)

new_arr = arr.reshape(3, 4)

print(new_arr)
print("Shape:", new_arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


## 4. flatten()

`flatten()` converts a multidimensional array into a 1D array.

It creates a new copy of the data.

In [5]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.flatten()

print("Original array:")
print(arr)

print("\nFlattened array:")
print(flat)

Original array:
[[1 2 3]
 [4 5 6]]

Flattened array:
[1 2 3 4 5 6]


## 5. ravel()

`ravel()` also converts an array into 1D.

Unlike `flatten()`, `ravel()` usually returns a view when possible.

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = arr.ravel()

print(flat)

[1 2 3 4 5 6]


## 6. reshape(-1)

`-1` tells NumPy to automatically calculate that dimension.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, -1)

print(new_arr)
print("Shape:", new_arr.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## Summary

- `reshape()` → changes array shape
- `flatten()` → converts to 1D and creates a copy
- `ravel()` → converts to 1D and usually returns a view
- `-1` → lets NumPy calculate the dimension automatically