# NumPy Broadcasting

Broadcasting allows NumPy to perform operations between arrays
of different but compatible shapes.

This is very important in Machine Learning because
we frequently perform mathematical operations on arrays.

In [2]:
import numpy as np

## 1. Adding a Number to an Array

Normally, we might think we need a loop to add a number
to every element.

NumPy can do this automatically using broadcasting.

In [3]:
arr = np.array([1, 2, 3, 4, 5])

result = arr + 10

print(result)

[11 12 13 14 15]


## 2. Multiplication

Broadcasting also works with multiplication.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

result = arr * 2

print(result)

[ 2  4  6  8 10]


## 3. Array + Array

Two arrays with the same shape can be added element by element.

In [5]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

result = a + b

print(result)

[11 22 33]


## 4. Broadcasting with a 2D Array

A single number is broadcast to every element of the matrix.

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = arr + 10

print(result)

[[11 12 13]
 [14 15 16]]


## 5. Broadcasting with a Row

In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row = np.array([10, 20, 30])

result = arr + row

print(result)

[[11 22 33]
 [14 25 36]]


## Why Broadcasting Matters in ML

Broadcasting is commonly used for:

- Feature scaling
- Normalization
- Mathematical transformations
- Matrix calculations
- Neural network operations

Example:

If we have many data points and want to subtract the mean,
NumPy can perform the operation efficiently without writing loops.

## Summary

Broadcasting allows NumPy to perform operations on arrays
with compatible shapes without manually writing loops.