# NumPy Random Numbers

NumPy provides the `random` module for generating random numbers.

Random numbers are very important in Machine Learning,
especially for:
- Initializing model parameters
- Creating test data
- Simulations
- Sampling

In [1]:
import numpy as np

## 1. Random Float

`np.random.rand()` generates random numbers between 0 and 1.

In [4]:
number = np.random.rand()

print(number)

0.8298729147256415


## 2. Multiple Random Numbers

In [5]:
numbers = np.random.rand(5)

print(numbers)

[0.39479108 0.25664163 0.67316169 0.07001354 0.0744551 ]


## 3. Random Integers

`np.random.randint()` generates random integer values.

Syntax:

np.random.randint(start, end, size)

In [8]:
numbers = np.random.randint(1, 10, size=5)

print(numbers)

[9 5 1 2 8]


## 4. Random Numbers in a Matrix

In [9]:
matrix = np.random.randint(1, 100, size=(3, 3))

print(matrix)

[[89 85 95]
 [ 2  6 47]
 [63 87 85]]


## 5. Normal Distribution

`np.random.normal()` generates values following a normal distribution.

A normal distribution is commonly used in statistics and ML.

In [10]:
numbers = np.random.normal(
    loc=0,
    scale=1,
    size=10
)

print(numbers)

[ 0.44832079  1.54061848  2.38129565 -0.0571014  -1.83092084 -1.23153433
  0.96609804 -0.88340333 -0.65959145  0.48599055]


## 6. Random Seed

Random numbers normally change every time we run the code.

A seed allows us to reproduce the same random numbers.

In [13]:
np.random.seed(42)

print(np.random.rand(5))

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


## Summary

- `np.random.rand()` → random floats between 0 and 1
- `np.random.randint()` → random integers
- `np.random.normal()` → normally distributed values
- `np.random.seed()` → makes random results reproducible