# NumPy Linear Algebra

Linear algebra is one of the mathematical foundations
of Machine Learning and Deep Learning.

In this notebook, we will learn:

- dot product
- matrix multiplication
- transpose
- basic matrix operations

In [1]:
import numpy as np

## 1. Dot Product

The dot product multiplies corresponding elements
and adds the results.

Example:

[1, 2, 3] · [4, 5, 6]

= (1×4) + (2×5) + (3×6)

= 32

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)

print(result)

32


## 2. Matrix Multiplication

`np.matmul()` performs matrix multiplication.

The dimensions of the matrices must be compatible.

In [3]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(A, B)

print(result)

[[19 22]
 [43 50]]


## 3. Matrix Multiplication Using @

Python provides the `@` operator for matrix multiplication.

In [4]:
result = A @ B

print(result)

[[19 22]
 [43 50]]


## 4. Transpose

Transpose changes rows into columns
and columns into rows.

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(A)

print("\nTranspose:")
print(A.T)

Original:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]


## 5. Shape Before and After Transpose

In [6]:
print("Original shape:", A.shape)
print("Transpose shape:", A.T.shape)

Original shape: (2, 3)
Transpose shape: (3, 2)


## 6. Matrix Multiplication Example

Let's multiply two matrices manually using NumPy.

In [7]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 3]
])

result = A @ B

print(result)

[[ 4  6]
 [10 12]]


## Why Linear Algebra Matters in ML

Machine Learning uses mathematical operations involving:

- Vectors
- Matrices
- Dot products
- Matrix multiplication

For example, a simple linear model can be represented as:

y = Xw + b

Where:

X = input data
w = weights
b = bias
y = prediction

NumPy allows us to perform these operations efficiently.

# Summary

Important functions/operators:

- `np.dot()` → dot product
- `np.matmul()` → matrix multiplication
- `@` → matrix multiplication
- `.T` → transpose

These concepts will become very important when learning
Machine Learning and Deep Learning.