# NumPy Creating Arrays

# Create a NumPy ndarray Object

In [1]:
# We can create a NumPy ndarray object by using the array() function.
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [2]:
print(type(arr))

<class 'numpy.ndarray'>


 To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [3]:
arr = np.array((1,2,3,4,5,6,7,8))
print(arr)

[1 2 3 4 5 6 7 8]


# Dimensions in Arrays

# 0-D Arrays


In [4]:
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(45)
print(arr)

45


# 1-D Arrays

In [5]:
# Create 1-D arrays
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [6]:
# These are often used to represent matrix or 2nd order tensors.
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays

In [7]:
# These are often used to represent a 3rd order tensor.
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1,2,3],[4,5,6]], [[1,4,7],[3,6,7]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 4 7]
  [3 6 7]]]


# Check Number of Dimensions?

In [9]:
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays

In [11]:
# When the array is created, you can define the number of dimensions by using the ndmin argument.
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [12]:
# size
arr.size

4

In [13]:
# itemsize
arr.itemsize

8