# NumPy Data Types


## Data Types in Python
    By default Python have these data types:
    
        strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
        integer - used to represent integer numbers. e.g. -1, -2, -3
        float - used to represent real numbers. e.g. 1.2, 42.42
        boolean - used to represent True or False.
        complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy

    NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
        i - integer
        b - boolean
        u - unsigned integer
        f - float
        c - complex float
        m - timedelta
        M - datetime
        O - object
        S - string
        U - unicode string
        V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [2]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


## Creating Arrays With a Defined Data Type

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


For i, u, f, S and U we can define size as well.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


## What if a Value Can Not Be Converted?

In [6]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

## Converting Data Type on Existing Arrays

In [7]:
# The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [9]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
